version: "3"
name: "people-test"

services:
  rabbitmq:
    image: rabbitmq:3.12.2-management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 5
  postgresserver:
    image: postgres:16.0-alpine3.18
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  postgresclient:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=Cde32wsxza1
    ports:
      - "5050:80"
  identity:
    build:
      context: ../back
      dockerfile: ../back/People.Identity/Dockerfile
    restart: always
    healthcheck:
      test: curl --fail http://identity:5279/healthz || exit
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 15s
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "5279:5279"
  corporate:
    build:
      context: ../back
      dockerfile: ../back/People.Corporate/Dockerfile
    restart: always
    healthcheck:
      test: curl --fail http://corporate:5762/healthz || exit
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 15s
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "5762:5762"
  points:
    build:
      context: ../back
      dockerfile: ../back/People.Points/Dockerfile
    restart: always
    volumes:
      - staticbackdata:/app
    healthcheck:
      test: curl --fail http://points:5134/healthz || exit
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 15s
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "5134:5134"
  nginx:
    build:
      context: ../nginx
      dockerfile: ../nginx/Dockerfile_dev
    ports:
      - 8080:8080
    restart: always
    depends_on:
      identity:
        condition: service_healthy
      corporate:
        condition: service_healthy
      points:
        condition: service_healthy
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

volumes:
  rabbitmqdata:
  staticbackdata:
